// Copies the root static app (the same files served on GitHub Pages) into
// www/, the webDir Capacitor's native shells load. www/ is gitignored and
// regenerated by this script rather than committed, so there's exactly one
// source of truth for the app itself — this only ever copies, never edits.
import { cpSync, rmSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const wwwDir = join(root, "www");

const FILES = ["index.html", "app.js", "manifest.json", "sw.js"];
const DIRS = ["vendor", "icons"];

rmSync(wwwDir, { recursive: true, force: true });
mkdirSync(wwwDir, { recursive: true });

for (const f of FILES) {
  const src = join(root, f);
  if (existsSync(src)) cpSync(src, join(wwwDir, f));
}
for (const d of DIRS) {
  const src = join(root, d);
  if (existsSync(src)) cpSync(src, join(wwwDir, d), { recursive: true });
}

console.log(`Synced ${FILES.length} files and ${DIRS.length} directories into www/`);
